# Site settings
name: Brandon Ho
title: Brandon Ho | Software Engineer
description: a Computer Engineering Student at University of California, San Diego
url: https://brandonho667.github.io/
baseurl: ''
email: b1ho@ucsd.edu
cover: https://brandonho667.github.io/img/og.png
logo: https://brandonho667.github.io/img/emojis/technologist.png
resume: https://brandonho667.github.io/resume.pdf
social:
  - title: email
    url: mailto:b1ho@gmail.com
  - title: github
    url: https://github.com/brandonho667
  - title: linkedin
    url: https://www.linkedin.com/in/bbho

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
